Xml generator
yshrsmz/simple-preferences pull request #12
Opened 2017-03-26 15:09 UTC by niknetniko

This is a basic xml resource generator: all options will be generated in the same file, optionally with a prefix.

Note: I didn't write a test, since I'm not entirely sure how I should test it.

2017-03-29 13:21 UTC, yshrsmz commented
Sorry for being late, I've been busy these days...
will look into this next weekend :bow:

2017-04-03 04:06 UTC, yshrsmz requested changes
> Note: I didn't write a test, since I'm not entirely sure how I should test it.

Yeah, I too not sure about how should we test this feature :thinking: 
But for now it's ok if new feature does not break existing test cases.

2017-04-03 04:06 UTC, yshrsmz commented on annotations/src/main/java/net/yslibrary/simplepreferences/annotation/Preferences.java
> +  String resourcePrefix() default "pref_";
I wonder if this resource related config should not be included in `@Preferences` annotation.
May be we'd better create new `@PreferencesResource` annotation to enable this feature.
What do you think about it?

2017-04-03 04:06 UTC, yshrsmz commented on processor/src/main/java/net/yslibrary/simplepreferences/processor/SimplePreferencesProcessor.java
> +    System.out.println("PATH: variant: " + variant);
this should be printed via messanger. 
you need to create new `note` method if you want this info to be displayed to users.
check `SimplePreferencesProcessor#error` method for the reference.

2017-04-03 04:06 UTC, yshrsmz commented on processor/src/main/java/net/yslibrary/simplepreferences/processor/SimplePreferencesProcessor.java
> +    while(!basePath.endsWith("generated")) {
here we get NPE when running test. (`./gradlew processor:test --stacktrace`)
At least we need to avoid breaking current test cases.

2017-04-16 21:20 UTC, niknetniko commented on annotations/src/main/java/net/yslibrary/simplepreferences/annotation/Preferences.java
> +  String resourcePrefix() default "pref_";
That's indeed a good idea, I'll change it

2017-04-16 21:20 UTC, niknetniko commented on processor/src/main/java/net/yslibrary/simplepreferences/processor/SimplePreferencesProcessor.java
> +    while(!basePath.endsWith("generated")) {
I'll look into this

2017-04-16 21:20 UTC, niknetniko commented on processor/src/main/java/net/yslibrary/simplepreferences/processor/SimplePreferencesProcessor.java
> +    System.out.println("PATH: variant: " + variant);
My bad, this is a debug statement I forgot to remove

2017-04-16 22:04 UTC, niknetniko commented
Unfortunately, the generated file is not actually included in the final apk, so this does effectively nothing. I will investigate some if this is possible or not.

2017-04-16 22:04 UTC, closed without merging